services:
  django:
    build: ./app
    container_name: djangoapp
    image: vassgps/webapp:${TAG:-latest}
    volumes:
      - ./app:/home/app/web
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    env_file:
      - ./app/.env
    ports:
      - "8000:8000"
    networks:
      - nginx_network
      - database_network
    depends_on:
      - database

  nginx:
    image: nginx:1.25-alpine
    container_name: nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - "80:80"
    depends_on:
      - django
    networks:
      - nginx_network

  database:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    container_name: database
    volumes:
      - ./database/postgres:/var/lib/postgresql/data
    env_file:
      - ./app/.env
    ports:
      - "5432:5432"
    networks:
      - database_network

networks:
  nginx_network:
    driver: bridge
  database_network:
    driver: bridge

volumes:
  static_volume:
  media_volume:
