services:
  django:
    build: ./app
    container_name: djangoapp
    volumes:
      - ./app:/home/app/web
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    env_file:
      - ./app/.env
    ports:
      - "8000:8000"
    networks:
      - webapp_network

volumes:
  static_volume:
  media_volume:

networks:
  webapp_network:
    driver: bridge
